name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Pages
      uses: actions/setup-pages@v1

    - name: Build and Deploy
      run: |
        mkdir -p public
        cp -r * public
        echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; URL=/portfolio/"></head></html>' > public/index.html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: public

    - name: Deploy
      uses: actions/deploy-pages@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
